#!/usr/bin/env python3
"""CLI for the x CTO-to-code loop state helper."""

from __future__ import annotations

import argparse
import sys

from x_state_brief import command_brief
from x_state_commands import *
from x_state_packages import command_package


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage x CTO-to-code loop state")
    sub = parser.add_subparsers(required=True)

    start = sub.add_parser("start", help="create a CTO-to-code run")
    start.add_argument("--goal", required=True)
    start.add_argument("--directive")
    start.add_argument("--success")
    start.add_argument("--constraints")
    start.add_argument("--short-goal")
    start.add_argument("--run-id")
    start.add_argument("--dry-run", action="store_true")
    start.set_defaults(func=command_start)

    status = sub.add_parser("status", help="show x status")
    status.add_argument("--run-id")
    status.set_defaults(func=command_status)

    resume = sub.add_parser("resume", help="print compact context for resuming a run")
    resume.add_argument("--run-id")
    resume.set_defaults(func=command_resume)

    ledger = sub.add_parser("ledger", help="show or update the x ledger")
    ledger.add_argument("--show", action="store_true")
    ledger.add_argument("--name")
    ledger.add_argument("--content")
    ledger.add_argument("--content-file")
    ledger.add_argument("--dry-run", action="store_true")
    ledger.set_defaults(func=command_ledger)

    section = sub.add_parser("section", help="replace a named markdown section in a run")
    section.add_argument("--run-id")
    section.add_argument("--name", required=True)
    section.add_argument("--content")
    section.add_argument("--content-file")
    section.add_argument("--status")
    section.add_argument("--phase")
    section.add_argument("--needs-user", choices=["yes", "no"])
    section.add_argument("--dry-run", action="store_true")
    section.set_defaults(func=command_section)

    brief = sub.add_parser("brief", help="create a CTO Intake Brief")
    brief.add_argument("--title", required=True)
    brief.add_argument("--cto-questions", required=True)
    brief.add_argument("--options", required=True)
    brief.add_argument("--recommendation", required=True)
    brief.add_argument("--risks", required=True)
    brief.add_argument("--root-decisions-needed", required=True)
    brief.add_argument("--accepted-direction")
    brief.add_argument("--status", default="draft", choices=["draft", "accepted", "blocked", "superseded"])
    brief.add_argument("--run-id")
    brief.add_argument("--brief-id")
    brief.add_argument("--package-id")
    brief.add_argument("--needs-user", choices=["yes", "no"])
    brief.add_argument("--next-action")
    brief.add_argument("--dry-run", action="store_true")
    brief.set_defaults(func=command_brief)

    contract = sub.add_parser("contract", help="create a Technical Contract")
    contract.add_argument("--title", required=True)
    contract.add_argument("--goal", required=True)
    contract.add_argument("--repo-intake", required=True)
    contract.add_argument("--codebase-findings", required=True)
    contract.add_argument("--allowed-boundaries", required=True)
    contract.add_argument("--forbidden-boundaries", required=True)
    contract.add_argument("--reversible-path", required=True)
    contract.add_argument("--verification", required=True)
    contract.add_argument("--loopback", required=True)
    contract.add_argument("--root-escalations")
    contract.add_argument("--status", default="active", choices=["active", "blocked", "superseded"])
    contract.add_argument("--run-id")
    contract.add_argument("--brief-id")
    contract.add_argument("--contract-id")
    contract.add_argument("--needs-user", choices=["yes", "no"])
    contract.add_argument("--next-action")
    contract.add_argument("--dry-run", action="store_true")
    contract.set_defaults(func=command_contract)

    task = sub.add_parser("task", help="create an Engineer Task")
    task.add_argument("--title", required=True)
    task.add_argument("--goal", required=True)
    task.add_argument("--allowed-scope", required=True)
    task.add_argument("--forbidden-scope", required=True)
    task.add_argument("--requirements", required=True)
    task.add_argument("--verification", required=True)
    task.add_argument("--done-evidence", required=True)
    task.add_argument("--status", default="active", choices=["active", "blocked", "done", "superseded"])
    task.add_argument("--run-id")
    task.add_argument("--contract-id")
    task.add_argument("--task-id")
    task.add_argument("--needs-user", choices=["yes", "no"])
    task.add_argument("--next-action")
    task.add_argument("--dry-run", action="store_true")
    task.set_defaults(func=command_task)

    iteration_start = sub.add_parser("iteration-start", help="start an implementation or fix iteration")
    iteration_start.add_argument("--task-id", required=True)
    iteration_start.add_argument("--kind", required=True, choices=["implementation", "fix"])
    iteration_start.add_argument("--title", required=True)
    iteration_start.add_argument("--goal")
    iteration_start.add_argument("--source-review-id")
    iteration_start.add_argument("--agent-policy", default="fresh", choices=["fresh", "reuse"])
    iteration_start.add_argument("--iteration-id")
    iteration_start.add_argument("--needs-user", choices=["yes", "no"])
    iteration_start.add_argument("--next-action")
    iteration_start.add_argument("--dry-run", action="store_true")
    iteration_start.set_defaults(func=command_iteration_start)

    iteration_result = sub.add_parser("iteration-result", help="record iteration patch evidence")
    iteration_result.add_argument("--iteration-id", required=True)
    iteration_result.add_argument("--changed-files", required=True)
    iteration_result.add_argument("--summary", required=True)
    iteration_result.add_argument("--verification", required=True)
    iteration_result.add_argument("--residual-risk", required=True)
    iteration_result.add_argument("--blockers")
    iteration_result.add_argument("--status", default="done", choices=["done", "blocked"])
    iteration_result.add_argument("--needs-user", choices=["yes", "no"])
    iteration_result.add_argument("--next-action")
    iteration_result.add_argument("--dry-run", action="store_true")
    iteration_result.set_defaults(func=command_iteration_result)

    task_result = sub.add_parser("task-result", help="record engineer patch evidence")
    task_result.add_argument("--task-id", required=True)
    task_result.add_argument("--iteration-id")
    task_result.add_argument("--changed-files", required=True)
    task_result.add_argument("--summary", required=True)
    task_result.add_argument("--verification", required=True)
    task_result.add_argument("--residual-risk", required=True)
    task_result.add_argument("--blockers")
    task_result.add_argument("--status", default="done", choices=["done", "blocked"])
    task_result.add_argument("--needs-user", choices=["yes", "no"])
    task_result.add_argument("--next-action")
    task_result.add_argument("--dry-run", action="store_true")
    task_result.set_defaults(func=command_task_result)

    package = sub.add_parser("package", help="create a subagent input package")
    package.add_argument("--role", required=True, choices=["cto", "engineer", "reviewer"])
    package.add_argument("--run-id")
    package.add_argument("--task-id")
    package.add_argument("--iteration-id")
    package.add_argument("--review-id")
    package.add_argument("--title")
    package.add_argument("--package-id")
    package.add_argument("--diff-stat")
    package.add_argument("--diff-stat-file")
    package.add_argument("--diff")
    package.add_argument("--diff-file")
    package.add_argument("--verification")
    package.add_argument("--verification-file")
    package.add_argument("--notes")
    package.add_argument("--notes-file")
    package.add_argument("--next-action")
    package.add_argument("--dry-run", action="store_true")
    package.set_defaults(func=command_package)

    review = sub.add_parser("review", help="create Review Findings")
    review.add_argument("--title", required=True)
    review.add_argument("--summary", required=True)
    review.add_argument("--recommendation", required=True, choices=["ready", "changes-requested", "blocked"])
    review.add_argument("--reviewed-diff", required=True)
    review.add_argument("--verification", required=True)
    review.add_argument("--blocking-findings")
    review.add_argument("--non-blocking-findings")
    review.add_argument("--residual-risk")
    review.add_argument("--status", default="open", choices=["open", "addressed", "accepted"])
    review.add_argument("--run-id")
    review.add_argument("--task-id")
    review.add_argument("--iteration-id")
    review.add_argument("--review-id")
    review.add_argument("--loopback-target", choices=["engineer", "cto", "root", "none"])
    review.add_argument("--needs-user", choices=["yes", "no"])
    review.add_argument("--next-action")
    review.add_argument("--dry-run", action="store_true")
    review.set_defaults(func=command_review)

    gate = sub.add_parser("gate", help="run an engineering gate")
    gate.add_argument("--mode", required=True, choices=["merge-ready"])
    gate.add_argument("--run-id")
    gate.add_argument("--dry-run", action="store_true")
    gate.set_defaults(func=command_gate)

    checkpoint = sub.add_parser("checkpoint", help="write a ledger and run checkpoint")
    checkpoint.add_argument("--run-id")
    checkpoint.add_argument("--summary", required=True)
    checkpoint.add_argument("--next-action")
    checkpoint.add_argument("--phase")
    checkpoint.add_argument("--needs-user", choices=["yes", "no"])
    checkpoint.add_argument("--dry-run", action="store_true")
    checkpoint.set_defaults(func=command_checkpoint)

    redirect = sub.add_parser("redirect", help="record a root redirect")
    redirect.add_argument("--run-id")
    redirect.add_argument("--note", required=True)
    redirect.add_argument("--dry-run", action="store_true")
    redirect.set_defaults(func=command_redirect)

    risk = sub.add_parser("risk", help="create a risk record")
    risk.add_argument("--title", required=True)
    risk.add_argument("--impact")
    risk.add_argument("--mitigation")
    risk.add_argument("--owner")
    risk.add_argument("--severity", default="medium", choices=["low", "medium", "high", "critical"])
    risk.add_argument("--status", default="open", choices=["open", "mitigating", "closed", "accepted"])
    risk.add_argument("--run-id")
    risk.add_argument("--risk-id")
    risk.add_argument("--dry-run", action="store_true")
    risk.set_defaults(func=command_risk)

    decision = sub.add_parser("decision", help="create a durable root decision record")
    decision.add_argument("--title", required=True)
    decision.add_argument("--decision", required=True)
    decision.add_argument("--context")
    decision.add_argument("--rationale")
    decision.add_argument("--consequences")
    decision.add_argument("--status", default="accepted")
    decision.add_argument("--run-id")
    decision.add_argument("--decision-id")
    decision.add_argument("--dry-run", action="store_true")
    decision.set_defaults(func=command_decision)

    close = sub.add_parser("close", help="close a run")
    close.add_argument("--run-id")
    close.add_argument("--status", default="accepted", choices=["accepted", "blocked", "closed", "superseded"])
    close.add_argument("--summary", required=True)
    close.add_argument("--dry-run", action="store_true")
    close.set_defaults(func=command_close)

    return parser


def main() -> None:
    args = build_parser().parse_args()
    try:
        args.func(args)
    except BrokenPipeError:
        sys.exit(1)


if __name__ == "__main__":
    main()
