#!/usr/bin/env python3
"""CLI for the x architect-to-code loop state helper."""

from __future__ import annotations

import argparse
import sys

from x_state_brief import command_brief
from x_state_audit import command_audit
from x_state_cleanup import command_cleanup_worktrees
from x_state_commands import *
from x_state_directives import command_architect_directive
from x_state_discussion import (
    ARCHITECT_INTAKE_STATUSES,
    DISCUSSION_MODES,
    DISCUSSION_STATUSES,
    DISCUSSION_TURN_KINDS,
    ROLE_BRIEF_STATUSES,
    command_architect_intake,
    command_board,
    command_discussion_start,
    command_discussion_show,
    command_discussion_synthesize,
    command_discussion_turn,
    command_role_list,
    command_role_brief,
    command_role_set,
    command_role_show,
)
from x_state_execution import (
    command_architect_gate,
    command_architect_review,
    command_execution_plan,
    command_lane_start,
    command_lane_status,
    command_lane_update,
)
from x_state_integration import command_integrate
from x_state_mailbox import MESSAGE_KINDS, MESSAGE_STATUSES, command_mailbox_list, command_mailbox_resolve, command_mailbox_send
from x_state_packages import command_package
from x_state_reviews import command_review


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage x architect-to-code loop state")
    sub = parser.add_subparsers(required=True)

    start = sub.add_parser("start", help="create an architect-to-code run")
    start.add_argument("--goal")
    start.add_argument("--directive")
    start.add_argument("--success")
    start.add_argument("--constraints")
    start.add_argument("--short-goal")
    start.add_argument("--run-id")
    start.add_argument("--dry-run", action="store_true")
    start.set_defaults(func=command_start)

    status = sub.add_parser("status", help="show x status")
    status.add_argument("--run-id")
    status.set_defaults(func=command_status)

    doctor = sub.add_parser("doctor", help="show x project binding and install diagnostics")
    doctor.set_defaults(func=command_doctor)

    resume = sub.add_parser("resume", help="print compact context for resuming a run")
    resume.add_argument("--run-id")
    resume.set_defaults(func=command_resume)

    ledger = sub.add_parser("ledger", help="show or update the x ledger")
    ledger.add_argument("--show", action="store_true")
    ledger.add_argument("--name")
    ledger.add_argument("--content")
    ledger.add_argument("--content-file")
    ledger.add_argument("--dry-run", action="store_true")
    ledger.set_defaults(func=command_ledger)

    role_list = sub.add_parser("role-list", help="list configured interaction role cards")
    role_list.set_defaults(func=command_role_list)

    role_show = sub.add_parser("role-show", help="show one interaction role card")
    role_show.add_argument("role")
    role_show.set_defaults(func=command_role_show)

    role_set = sub.add_parser("role-set", help="create or replace one runtime interaction role card")
    role_set.add_argument("role")
    role_set.add_argument("--body")
    role_set.add_argument("--body-file")
    role_set.add_argument("--responsibilities")
    role_set.add_argument("--use-when")
    role_set.add_argument("--avoid-when")
    role_set.add_argument("--inputs-to-inspect")
    role_set.add_argument("--focus")
    role_set.add_argument("--must-challenge")
    role_set.add_argument("--operating-posture")
    role_set.add_argument("--evidence-standard")
    role_set.add_argument("--handoff-value")
    role_set.add_argument("--failure-modes")
    role_set.add_argument("--out-of-bounds")
    role_set.add_argument("--output-format")
    role_set.add_argument("--dry-run", action="store_true")
    role_set.set_defaults(func=command_role_set)

    discussion_start = sub.add_parser("discussion-start", help="create a root interaction record with discussion-compatible naming")
    discussion_start.add_argument("--mode", required=True, choices=DISCUSSION_MODES)
    discussion_start.add_argument("--title", required=True)
    discussion_start.add_argument("--agenda", required=True)
    discussion_start.add_argument("--participants", nargs="+", required=True)
    discussion_start.add_argument("--status", default="active", choices=DISCUSSION_STATUSES)
    discussion_start.add_argument("--run-id")
    discussion_start.add_argument("--discussion-id")
    discussion_start.add_argument("--dry-run", action="store_true")
    discussion_start.set_defaults(func=command_discussion_start)

    interaction_start = sub.add_parser("interaction-start", help="create a root interaction record")
    interaction_start.add_argument("--mode", required=True, choices=DISCUSSION_MODES)
    interaction_start.add_argument("--title", required=True)
    interaction_start.add_argument("--agenda", required=True)
    interaction_start.add_argument("--participants", nargs="+", required=True)
    interaction_start.add_argument("--status", default="active", choices=DISCUSSION_STATUSES)
    interaction_start.add_argument("--run-id")
    interaction_start.add_argument("--interaction-id", dest="discussion_id")
    interaction_start.add_argument("--discussion-id", dest="discussion_id")
    interaction_start.add_argument("--dry-run", action="store_true")
    interaction_start.set_defaults(func=command_discussion_start)

    discussion_turn = sub.add_parser("discussion-turn", help="record one interaction turn with discussion-compatible naming")
    discussion_turn.add_argument("--discussion-id", dest="discussion_id")
    discussion_turn.add_argument("--interaction-id", dest="discussion_id")
    discussion_turn.add_argument("--actor", required=True)
    discussion_turn.add_argument("--to")
    discussion_turn.add_argument("--turn-kind", required=True, choices=DISCUSSION_TURN_KINDS)
    discussion_turn.add_argument("--body")
    discussion_turn.add_argument("--body-file")
    discussion_turn.add_argument("--dry-run", action="store_true")
    discussion_turn.set_defaults(func=command_discussion_turn)

    discussion_show = sub.add_parser("discussion-show", help="show the full interaction transcript with discussion-compatible naming")
    discussion_show.add_argument("--discussion-id", dest="discussion_id")
    discussion_show.add_argument("--interaction-id", dest="discussion_id")
    discussion_show.add_argument("--full", action="store_true")
    discussion_show.set_defaults(func=command_discussion_show)

    interaction_turn = sub.add_parser("interaction-turn", help="record one interaction turn")
    interaction_turn.add_argument("--interaction-id", dest="discussion_id")
    interaction_turn.add_argument("--discussion-id", dest="discussion_id")
    interaction_turn.add_argument("--actor", required=True)
    interaction_turn.add_argument("--to")
    interaction_turn.add_argument("--turn-kind", required=True, choices=DISCUSSION_TURN_KINDS)
    interaction_turn.add_argument("--body")
    interaction_turn.add_argument("--body-file")
    interaction_turn.add_argument("--dry-run", action="store_true")
    interaction_turn.set_defaults(func=command_discussion_turn)

    interaction_show = sub.add_parser("interaction-show", help="show the full interaction transcript")
    interaction_show.add_argument("--interaction-id", dest="discussion_id")
    interaction_show.add_argument("--discussion-id", dest="discussion_id")
    interaction_show.add_argument("--full", action="store_true")
    interaction_show.set_defaults(func=command_discussion_show)

    role_brief = sub.add_parser("role-brief", help="create a durable interaction role brief")
    role_brief.add_argument("--discussion-id", dest="discussion_id")
    role_brief.add_argument("--interaction-id", dest="discussion_id")
    role_brief.add_argument("--role", required=True)
    role_brief.add_argument("--title", required=True)
    role_brief.add_argument("--recommendation", required=True)
    role_brief.add_argument("--rationale", required=True)
    role_brief.add_argument("--rejected-options", required=True)
    role_brief.add_argument("--risks", required=True)
    role_brief.add_argument("--decisions-needed", required=True)
    role_brief.add_argument("--implications-for-architect", required=True)
    role_brief.add_argument("--strongest-objection", required=True)
    role_brief.add_argument("--weakest-assumption", required=True)
    role_brief.add_argument("--evidence-to-change", required=True)
    role_brief.add_argument("--status", default="ready", choices=ROLE_BRIEF_STATUSES)
    role_brief.add_argument("--brief-id")
    role_brief.add_argument("--dry-run", action="store_true")
    role_brief.set_defaults(func=command_role_brief)

    discussion_synthesize = sub.add_parser("discussion-synthesize", help="record interaction synthesis with discussion-compatible naming")
    discussion_synthesize.add_argument("--discussion-id", dest="discussion_id")
    discussion_synthesize.add_argument("--interaction-id", dest="discussion_id")
    discussion_synthesize.add_argument("--agreements", required=True)
    discussion_synthesize.add_argument("--conflicts", required=True)
    discussion_synthesize.add_argument("--rejected-options", required=True)
    discussion_synthesize.add_argument("--root-decisions-needed", required=True)
    discussion_synthesize.add_argument("--recommended-direction", required=True)
    discussion_synthesize.add_argument("--architect-intake-draft", required=True)
    discussion_synthesize.add_argument("--strongest-objection", required=True)
    discussion_synthesize.add_argument("--weakest-assumption", required=True)
    discussion_synthesize.add_argument("--evidence-to-change", required=True)
    discussion_synthesize.add_argument("--dry-run", action="store_true")
    discussion_synthesize.set_defaults(func=command_discussion_synthesize)

    interaction_summarize = sub.add_parser("interaction-summarize", help="record interaction synthesis/proposal")
    interaction_summarize.add_argument("--interaction-id", dest="discussion_id")
    interaction_summarize.add_argument("--discussion-id", dest="discussion_id")
    interaction_summarize.add_argument("--agreements", required=True)
    interaction_summarize.add_argument("--conflicts", required=True)
    interaction_summarize.add_argument("--rejected-options", required=True)
    interaction_summarize.add_argument("--root-decisions-needed", required=True)
    interaction_summarize.add_argument("--recommended-direction", required=True)
    interaction_summarize.add_argument("--architect-intake-draft", required=True)
    interaction_summarize.add_argument("--strongest-objection", required=True)
    interaction_summarize.add_argument("--weakest-assumption", required=True)
    interaction_summarize.add_argument("--evidence-to-change", required=True)
    interaction_summarize.add_argument("--dry-run", action="store_true")
    interaction_summarize.set_defaults(func=command_discussion_synthesize)

    architect_intake = sub.add_parser("architect-intake", help="create an architect intake from root decision")
    architect_intake.add_argument("--discussion-id", dest="discussion_id")
    architect_intake.add_argument("--interaction-id", dest="discussion_id")
    architect_intake.add_argument("--title", required=True)
    architect_intake.add_argument("--accepted-direction", required=True)
    architect_intake.add_argument("--architecture-input", required=True)
    architect_intake.add_argument("--scope-boundaries", required=True)
    architect_intake.add_argument("--non-goals", required=True)
    architect_intake.add_argument("--root-decisions", required=True)
    architect_intake.add_argument("--risks", required=True)
    architect_intake.add_argument("--handoff-to-architect", required=True)
    architect_intake.add_argument("--status", default="draft", choices=ARCHITECT_INTAKE_STATUSES)
    architect_intake.add_argument("--decision-id")
    architect_intake.add_argument("--intake-id")
    architect_intake.add_argument("--dry-run", action="store_true")
    architect_intake.set_defaults(func=command_architect_intake)

    board = sub.add_parser("board", help="show or write the root-facing board")
    board.add_argument("--write", action="store_true")
    board.add_argument("--dry-run", action="store_true")
    board.set_defaults(func=command_board)

    materialize = sub.add_parser("materialize", help="create and bind the integration worktree for an accepted architecture run")
    materialize.add_argument("--run-id")
    materialize.add_argument("--scope", required=True)
    materialize.add_argument("--branch")
    materialize.add_argument("--worktree")
    materialize.add_argument("--base")
    materialize.add_argument("--reuse-worktree", action="store_true")
    materialize.add_argument("--needs-user", choices=["yes", "no"])
    materialize.add_argument("--next-action")
    materialize.add_argument("--dry-run", action="store_true")
    materialize.set_defaults(func=command_materialize)

    section = sub.add_parser("section", help="replace a named markdown section in a run")
    section.add_argument("--run-id")
    section.add_argument("--name", required=True)
    section.add_argument("--content")
    section.add_argument("--content-file")
    section.add_argument("--status")
    section.add_argument("--phase")
    section.add_argument("--needs-user", choices=["yes", "no"])
    section.add_argument("--dry-run", action="store_true")
    section.set_defaults(func=command_section)

    brief = sub.add_parser("brief", help="create an Architecture Brief")
    brief.add_argument("--title", required=True)
    brief.add_argument("--architect-questions", required=True)
    brief.add_argument("--options", required=True)
    brief.add_argument("--recommendation", required=True)
    brief.add_argument("--risks", required=True)
    brief.add_argument("--root-decisions-needed", required=True)
    brief.add_argument("--accepted-direction")
    brief.add_argument("--status", default="draft", choices=["draft", "accepted", "blocked", "superseded"])
    brief.add_argument("--run-id")
    brief.add_argument("--brief-id")
    brief.add_argument("--package-id")
    brief.add_argument("--needs-user", choices=["yes", "no"])
    brief.add_argument("--next-action")
    brief.add_argument("--dry-run", action="store_true")
    brief.set_defaults(func=command_brief)

    contract = sub.add_parser("contract", help="create a Technical Contract")
    contract.add_argument("--title", required=True)
    contract.add_argument("--goal", required=True)
    contract.add_argument("--repo-intake", required=True)
    contract.add_argument("--codebase-findings", required=True)
    contract.add_argument("--allowed-boundaries", required=True)
    contract.add_argument("--forbidden-boundaries", required=True)
    contract.add_argument("--reversible-path", required=True)
    contract.add_argument("--verification", required=True)
    contract.add_argument("--loopback", required=True)
    contract.add_argument("--root-escalations")
    contract.add_argument("--status", default="active", choices=["active", "blocked", "superseded"])
    contract.add_argument("--run-id")
    contract.add_argument("--brief-id")
    contract.add_argument("--contract-id")
    contract.add_argument("--needs-user", choices=["yes", "no"])
    contract.add_argument("--next-action")
    contract.add_argument("--dry-run", action="store_true")
    contract.set_defaults(func=command_contract)

    task = sub.add_parser("task", help="create an Engineer Task")
    task.add_argument("--title", required=True)
    task.add_argument("--goal", required=True)
    task.add_argument("--allowed-scope", required=True)
    task.add_argument("--forbidden-scope", required=True)
    task.add_argument("--requirements", required=True)
    task.add_argument("--verification", required=True)
    task.add_argument("--done-evidence", required=True)
    task.add_argument("--status", default="active", choices=["active", "blocked", "done", "superseded"])
    task.add_argument("--run-id")
    task.add_argument("--contract-id")
    task.add_argument("--task-id")
    task.add_argument("--needs-user", choices=["yes", "no"])
    task.add_argument("--next-action")
    task.add_argument("--dry-run", action="store_true")
    task.set_defaults(func=command_task)

    execution_plan = sub.add_parser("execution-plan", help="create or update an Architect Execution Plan")
    execution_plan.add_argument("--run-id")
    execution_plan.add_argument("--plan-id")
    execution_plan.add_argument("--title")
    execution_plan.add_argument("--objective")
    execution_plan.add_argument("--parallel-lanes")
    execution_plan.add_argument("--dependency-graph")
    execution_plan.add_argument("--lane-ownership")
    execution_plan.add_argument("--allowed-scope")
    execution_plan.add_argument("--forbidden-scope")
    execution_plan.add_argument("--expected-artifacts")
    execution_plan.add_argument("--verification-matrix")
    execution_plan.add_argument("--reviewer-criteria")
    execution_plan.add_argument("--architect-merge-criteria")
    execution_plan.add_argument("--integration-order")
    execution_plan.add_argument("--known-risks")
    execution_plan.add_argument("--loopback-triggers")
    execution_plan.add_argument("--blocked-recovery")
    execution_plan.add_argument("--root-decisions")
    execution_plan.add_argument("--final-verification-status", choices=["pending", "green", "red", "blocked"])
    execution_plan.add_argument("--final-verification")
    execution_plan.add_argument("--final-verification-file")
    execution_plan.add_argument("--status", choices=["active", "accepted", "blocked", "replan-required", "superseded"])
    execution_plan.add_argument("--next-action")
    execution_plan.add_argument("--dry-run", action="store_true")
    execution_plan.set_defaults(func=command_execution_plan)

    architect_gate = sub.add_parser("architect-gate", help="run the Architect Execution Plan readiness gate")
    architect_gate.add_argument("--run-id")
    architect_gate.add_argument("--dry-run", action="store_true")
    architect_gate.set_defaults(func=command_architect_gate)

    lane_start = sub.add_parser("lane-start", help="start a lane session/worktree from a gated Architect Execution Plan")
    lane_start.add_argument("--run-id")
    lane_start.add_argument("--lane-id", required=True)
    lane_start.add_argument("--task-id", required=True)
    lane_start.add_argument("--worktree")
    lane_start.add_argument("--branch")
    lane_start.add_argument("--reuse-worktree", action="store_true")
    lane_start.add_argument("--needs-user", choices=["yes", "no"])
    lane_start.add_argument("--next-action")
    lane_start.add_argument("--dry-run", action="store_true")
    lane_start.set_defaults(func=command_lane_start)

    lane_status = sub.add_parser("lane-status", help="show lane status for a run")
    lane_status.add_argument("--run-id")
    lane_status.set_defaults(func=command_lane_status)

    lane_update = sub.add_parser("lane-update", help="record an advisory lane heartbeat")
    lane_update.add_argument("--run-id")
    lane_update.add_argument("--lane-id", required=True)
    lane_update.add_argument("--actor", required=True, choices=["engineer", "reviewer", "architect", "main"])
    lane_update.add_argument("--session", required=True)
    lane_update.add_argument("--heartbeat-status", required=True, choices=["active", "reviewing", "blocked", "idle"])
    lane_update.add_argument("--activity", required=True)
    lane_update.add_argument("--blocker", required=True)
    lane_update.add_argument("--next-action", required=True)
    lane_update.add_argument("--dry-run", action="store_true")
    lane_update.set_defaults(func=command_lane_update)

    mailbox_send = sub.add_parser("mailbox-send", help="create a lightweight x mailbox message")
    mailbox_send.add_argument("--kind", required=True, choices=MESSAGE_KINDS)
    mailbox_send.add_argument("--from", dest="from_actor", required=True)
    mailbox_send.add_argument("--to", dest="to_actor", required=True)
    mailbox_send.add_argument("--summary", required=True)
    mailbox_send.add_argument("--body")
    mailbox_send.add_argument("--body-file")
    mailbox_send.add_argument("--related-artifacts")
    mailbox_send.add_argument("--related-artifacts-file")
    mailbox_send.add_argument("--run-id")
    mailbox_send.add_argument("--lane-id")
    mailbox_send.add_argument("--task-id")
    mailbox_send.add_argument("--attempt-id")
    mailbox_send.add_argument("--review-id")
    mailbox_send.add_argument("--session")
    mailbox_send.add_argument("--message-id")
    mailbox_send.add_argument("--status", default="open", choices=MESSAGE_STATUSES)
    mailbox_send.add_argument("--dry-run", action="store_true")
    mailbox_send.set_defaults(func=command_mailbox_send)

    mailbox_list = sub.add_parser("mailbox-list", help="list x mailbox messages")
    mailbox_list.add_argument("--run-id")
    mailbox_list.add_argument("--status", default="open", choices=[*MESSAGE_STATUSES, "all"])
    mailbox_list.add_argument("--kind", choices=MESSAGE_KINDS)
    mailbox_list.add_argument("--lane-id")
    mailbox_list.set_defaults(func=command_mailbox_list)

    mailbox_resolve = sub.add_parser("mailbox-resolve", help="mark an x mailbox message addressed or superseded")
    mailbox_resolve.add_argument("--message-id", required=True)
    mailbox_resolve.add_argument("--status", default="addressed", choices=["addressed", "superseded"])
    mailbox_resolve.add_argument("--resolution")
    mailbox_resolve.add_argument("--resolution-file")
    mailbox_resolve.add_argument("--run-id")
    mailbox_resolve.add_argument("--dry-run", action="store_true")
    mailbox_resolve.set_defaults(func=command_mailbox_resolve)

    attempt_start = sub.add_parser("attempt-start", help="start an implementation or fix attempt")
    attempt_start.add_argument("--task-id", required=True)
    attempt_start.add_argument("--lane-id")
    attempt_start.add_argument("--kind", required=True, choices=["implementation", "fix"])
    attempt_start.add_argument("--title", required=True)
    attempt_start.add_argument("--goal")
    attempt_start.add_argument("--source-review-id")
    attempt_start.add_argument("--source-architect-review-id")
    attempt_start.add_argument("--attempt-id")
    attempt_start.add_argument("--needs-user", choices=["yes", "no"])
    attempt_start.add_argument("--next-action")
    attempt_start.add_argument("--dry-run", action="store_true")
    attempt_start.set_defaults(func=command_attempt_start)

    attempt_result = sub.add_parser("attempt-result", help="record attempt evidence")
    attempt_result.add_argument("--attempt-id", required=True)
    attempt_result.add_argument("--changed-files", required=True)
    attempt_result.add_argument("--summary", required=True)
    attempt_result.add_argument("--verification", required=True)
    attempt_result.add_argument("--residual-risk", required=True)
    attempt_result.add_argument("--blockers")
    attempt_result.add_argument("--status", default="done", choices=["done", "blocked"])
    attempt_result.add_argument("--needs-user", choices=["yes", "no"])
    attempt_result.add_argument("--next-action")
    attempt_result.add_argument("--dry-run", action="store_true")
    attempt_result.set_defaults(func=command_attempt_result)

    package = sub.add_parser("package", help="create a role input package")
    package.add_argument("--role", required=True, choices=["architect", "engineer", "reviewer", "councilor"])
    package.add_argument("--run-id")
    package.add_argument("--discussion-id")
    package.add_argument("--interaction-id", dest="discussion_id")
    package.add_argument("--council-role")
    package.add_argument("--architect-intake-id")
    package.add_argument("--task-id")
    package.add_argument("--attempt-id")
    package.add_argument("--review-id")
    package.add_argument("--title")
    package.add_argument("--package-id")
    package.add_argument("--diff-stat")
    package.add_argument("--diff-stat-file")
    package.add_argument("--diff")
    package.add_argument("--diff-file")
    package.add_argument("--verification")
    package.add_argument("--verification-file")
    package.add_argument("--notes")
    package.add_argument("--notes-file")
    package.add_argument("--next-action")
    package.add_argument("--dry-run", action="store_true")
    package.set_defaults(func=command_package)

    review = sub.add_parser("review", help="create Review Findings")
    review.add_argument("--title", required=True)
    review.add_argument("--summary", required=True)
    review.add_argument("--recommendation", required=True, choices=["ready", "changes-requested", "blocked"])
    review.add_argument("--reviewed-diff", required=True)
    review.add_argument("--verification", required=True)
    review.add_argument("--blocking-findings")
    review.add_argument("--non-blocking-findings")
    review.add_argument("--residual-risk")
    review.add_argument("--status", default="open", choices=["open", "addressed", "accepted"])
    review.add_argument("--run-id")
    review.add_argument("--attempt-id", required=True)
    review.add_argument("--review-id")
    review.add_argument("--loopback-target", choices=["engineer", "architect", "root", "none"])
    review.add_argument("--needs-user", choices=["yes", "no"])
    review.add_argument("--next-action")
    review.add_argument("--dry-run", action="store_true")
    review.set_defaults(func=command_review)

    architect_review = sub.add_parser("architect-review", help="create Architect Integration Review for a lane attempt")
    architect_review.add_argument("--run-id")
    architect_review.add_argument("--lane-id", required=True)
    architect_review.add_argument("--attempt-id", required=True)
    architect_review.add_argument("--title", required=True)
    architect_review.add_argument("--summary", required=True)
    architect_review.add_argument("--recommendation", required=True, choices=["merge-ok", "changes-requested", "blocked", "replan"])
    architect_review.add_argument("--criteria", required=True)
    architect_review.add_argument("--verification", required=True)
    architect_review.add_argument("--integration-risk", required=True)
    architect_review.add_argument("--blocking-findings")
    architect_review.add_argument("--status", default="open", choices=["open", "addressed", "accepted"])
    architect_review.add_argument("--review-id")
    architect_review.add_argument("--needs-user", choices=["yes", "no"])
    architect_review.add_argument("--next-action")
    architect_review.add_argument("--dry-run", action="store_true")
    architect_review.set_defaults(func=command_architect_review)

    architect_directive = sub.add_parser("architect-directive", help="record and apply an architect control directive")
    architect_directive.add_argument("--run-id")
    architect_directive.add_argument("--directive-id")
    architect_directive.add_argument("--plan-id")
    architect_directive.add_argument("--lane-id")
    architect_directive.add_argument("--title", required=True)
    architect_directive.add_argument("--target", required=True, choices=["run", "plan", "lane"])
    architect_directive.add_argument(
        "--action",
        required=True,
        choices=[
            "continue",
            "parallelism-adjustment",
            "verification-adjustment",
            "pause-lane",
            "resume-lane",
            "replan",
            "root-decision",
            "request-more-evidence",
        ],
    )
    architect_directive.add_argument("--summary", required=True)
    architect_directive.add_argument("--instructions", required=True)
    architect_directive.add_argument("--acceptance", required=True)
    architect_directive.add_argument("--status", choices=["open", "addressed", "accepted", "superseded"])
    architect_directive.add_argument("--next-action")
    architect_directive.add_argument("--dry-run", action="store_true")
    architect_directive.set_defaults(func=command_architect_directive)

    integrate = sub.add_parser("integrate", help="integrate one architect-approved lane into the integration worktree")
    integrate.add_argument("--run-id")
    integrate.add_argument("--lane-id", required=True)
    integrate.add_argument("--notes")
    integrate.add_argument("--next-action")
    integrate.add_argument("--dry-run", action="store_true")
    integrate.set_defaults(func=command_integrate)

    gate = sub.add_parser("gate", help="run an engineering gate")
    gate.add_argument("--mode", required=True, choices=["merge-ready"])
    gate.add_argument("--run-id")
    gate.add_argument("--dry-run", action="store_true")
    gate.set_defaults(func=command_gate)

    checkpoint = sub.add_parser("checkpoint", help="write a ledger and run checkpoint")
    checkpoint.add_argument("--run-id")
    checkpoint.add_argument("--summary", required=True)
    checkpoint.add_argument("--next-action")
    checkpoint.add_argument("--phase")
    checkpoint.add_argument("--needs-user", choices=["yes", "no"])
    checkpoint.add_argument("--dry-run", action="store_true")
    checkpoint.set_defaults(func=command_checkpoint)

    redirect = sub.add_parser("redirect", help="record a root redirect")
    redirect.add_argument("--run-id")
    redirect.add_argument("--note", required=True)
    redirect.add_argument("--dry-run", action="store_true")
    redirect.set_defaults(func=command_redirect)

    risk = sub.add_parser("risk", help="create a risk record")
    risk.add_argument("--title", required=True)
    risk.add_argument("--impact")
    risk.add_argument("--mitigation")
    risk.add_argument("--owner")
    risk.add_argument("--severity", default="medium", choices=["low", "medium", "high", "critical"])
    risk.add_argument("--status", default="open", choices=["open", "mitigating", "closed", "accepted"])
    risk.add_argument("--run-id")
    risk.add_argument("--risk-id")
    risk.add_argument("--dry-run", action="store_true")
    risk.set_defaults(func=command_risk)

    decision = sub.add_parser("decision", help="create a durable root decision record")
    decision.add_argument("--title", required=True)
    decision.add_argument("--decision", required=True)
    decision.add_argument("--context")
    decision.add_argument("--rationale")
    decision.add_argument("--consequences")
    decision.add_argument("--status", default="accepted")
    decision.add_argument("--run-id")
    decision.add_argument("--discussion-id", dest="discussion_id")
    decision.add_argument("--interaction-id", dest="discussion_id")
    decision.add_argument("--architect-intake-id")
    decision.add_argument("--decision-id")
    decision.add_argument("--dry-run", action="store_true")
    decision.set_defaults(func=command_decision)

    close = sub.add_parser("close", help="close a run")
    close.add_argument("--run-id")
    close.add_argument("--status", default="accepted", choices=["accepted", "blocked", "closed", "superseded"])
    close.add_argument("--summary", required=True)
    close.add_argument("--dry-run", action="store_true")
    close.set_defaults(func=command_close)

    cleanup = sub.add_parser("cleanup-worktrees", help="remove clean integrated lane worktrees for a run")
    cleanup.add_argument("--run-id", required=True)
    cleanup.add_argument("--apply", action="store_true")
    cleanup.set_defaults(func=command_cleanup_worktrees)

    audit = sub.add_parser("audit", help="audit one run from x state and Codex local usage data")
    audit.add_argument("--run-id", required=True)
    audit.add_argument("--json", action="store_true")
    audit.add_argument("--write", action="store_true")
    audit.add_argument("--codex-state")
    audit.set_defaults(func=command_audit)

    return parser


def main() -> None:
    args = build_parser().parse_args()
    try:
        args.func(args)
    except BrokenPipeError:
        sys.exit(1)


if __name__ == "__main__":
    main()
